### ISSUE TITLE
Safari MultiPartyChat Stream Issue 

### ISSUE THREAD

**Issue by wooolfgang** [PhenixRTS/WebRoomDemo#1]
Hi,

I used this repo as a guideline for a project that we have, and we also used this particular version. A problem that I found with this code specifically is that it's not calling the pcast.subScribeToStream callback on safari whilst it does on chrome. Do you guys have any solutions, or do you just recommend to upgrade/migrate to the latest version of the sdk? Thanks!

```
return httpRequests
    .createStreamTokenForViewing(pcastStream.streamId, selfSessionId, latency)
    .then(({ streamToken }) => {
      return new Promise((res, rej) => {
        pcast.subscribeToStream(
          streamToken,
          (pcast, status, mediaStream) => {
            if (status === "ok") {
              res(mediaStream);
            } else {
              rej(status);
            }
          },
          {}
        );
      });
    });
```

**Comment by sempi** [comment]
Hi @wooolfgang 

Thanks for the note.

Can you elaborate the use case that you are trying to implement?

Do you have access to the slack support channel?

Looking forward to hear from you.

**Comment by wooolfgang** [comment]
Hi, thanks for the reply,

I don't have access but I'd love to join the slack channel.

Essentially I'm trying to make view live stream work on safari. This code above works well on chrome, and returns the mediaStream object with the callback. The problem is that on safari, the callback is not being executed on pcast.subscribe() despite the same code. When you run this WebRoomDemo, the streams on a room are not working on safari as well.

**Comment by sempi** [comment]
Hi @wooolfgang 

Slack should be setup shortly. Let's continue the discussion there.
